version: '3'

services: 
  server:
    build: ./src
    ports:
      - 5000:5000
    restart: always
    volumes: 
      - ./src:/usr/src
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"